spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xrc
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info
    org.hibernate.sql: DEBUG

data:
  max_voltage: 250
  min_voltage: 50
  max_attenuation_frequency: 10000000
  min_attenuation_frequency: 1
  doubleFormat: '#.##'