spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xrc
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      ttl: "PT24H"
      channels:


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info
    org.hibernate.sql: DEBUG

data:
  max_voltage: 250
  min_voltage: 50
  max_attenuation_frequency: 10000000
  min_attenuation_frequency: 1
  doubleFormat: '#.##'
  number_places: 2
  low_ren_limit: 0.25
  low_window_limit: 2.5
  not_demanded_protection: "Не требуется"
